### ISSUE TITLE
any news on this? offering help here...

### ISSUE THREAD

**Issue by 2075** [nupic-community/HMT.Julia#3]

**Comment by breznak** [comment]
@passiweinberger how's it going? @2075 offered to help out

**Comment by passiweinberger** [comment]
@2075 :D Howdee :) 👍 
@breznak Nope :D Did not find _any_ time so far to get this going! :( 
Feel free to give it a try, but i really can't assist you atm. :(

**Comment by nbro** [comment]
@passiweinberger It's been 3 years of non-development! You should try to get rid of this repo. It doesn't make sense to have a repo whose README file states that a project is in progress or under development, while it is not. You can ask @cogmission to delete his fork, before deleting this repo.

**Comment by rhyolight** [comment]
It is here if anyone wants to continue working on it. Feel free to update the README, but we're not deleting the repo.
